[package]
name = "benchmark_ct"
version = "0.1.0"
authors = ["valarauca <codylaeder@gmail.com>"]

[dependencies]
amd64_timer = { path="amd64_timer" }
consistenttime = "0.2.0"
clap = "2.19.2"
time = "0.1.35"
